### PR TITLE
Adapted to Minecraft v.1.11

### PR DESCRIPTION
**Pull request by supergvg**
This small fix is working for 1.11 version

### CODE REVIEW

**Comment by Brottweiler** [comment]
You might want to maintain your own fork; [minecraftforum.net/1290546?comment=686](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290546-presence-footsteps-an-overly-complicated-sound?comment=686)

**Comment by Brottweiler** [comment]
Might want to enable Issues on your repo, and also possibly Wiki and add the resourcepack(s) aswell. Not sure if you guys know how the expansionpacks work and if you can update and fix their bugs.

**Comment by supergvg** [comment]
Issues was enabled. GVG (Vitaly) will add some information to Wiki section a bit later.

**Comment by GVG** [comment]
@Brottweiler Are there any resource packs except for MSI_conversion.zip (MSI Converted to MAtmos for 1.9)? This is the only one I have.
You can add issues that you've found to our fork. Maybe we'll fix them someday.

**Comment by Brottweiler** [comment]
@GVG Other than [the ones in the wiki](https://github.com/Sollace/MAtmos/wiki#soundpacks), there is the default/original one `Matmos.Default.zip` located [hre](https://github.com/Sollace/MAtmos/releases/tag/r30d). This is the one I use.

**Pull request merged**
